import {
	Button,
  Card,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Typography,
} from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";

export default function Cuenta() {
  return (
    <>
      <Head>
        <title>Cuenta RUT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          width: "100%",
          minHeight: "100%",
        }}
      >
        <Card
          sx={{
            padding: "15px 30px",
            borderRadius: "8px",
            textAlign: "center",
          }}
        >
          <Typography variant="h5" sx={{ userSelect: "none" }}>
            Cuenta RUT
          </Typography>
          <Typography variant="h6" sx={{ userSelect: "none" }}>
            de la
          </Typography>
          <Typography variant="h5" sx={{ userSelect: "none" }}>
            Tía Gloria
          </Typography>
          <TableContainer component={Paper}>
            <Table sx={{ minWidth: "300px" }}>
              <TableBody>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Nombre:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">Gloria Salinas</Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Alias:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">Tía Gloria</Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>RUT:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">11.363.728-5</Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Correo electrónico:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">
                      gloria.contacto@gmail.com
                    </Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Banco:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">Banco Estado</Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Tipo de cuenta:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">Vista</Typography>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell component={"th"} scope={"row"}>
                    <Typography variant="body1" sx={{ userSelect: "none" }}>Número de cuenta:</Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="body1">11363728</Typography>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
					<Button sx={{ margin: '16px' }} variant={'contained'}><Typography variant="body1">COPIAR</Typography></Button>
        </Card>
      </Box>
    </>
  );
}
